server: ""        # leave empty (will be filled dynamically)
database: ""      # leave empty
user: ""          # leave empty
password: ""      # leave empty
connectionTimeout: 10000
pool:
  max: 10
  min: 0
  idleTimeoutMillis: 30000
options:
  # encrypt: true   # for azure
  trustServerCertificate: true  # change to true for local dev / self-signed certs
